#
#   Defines
#
BASEDIR		:=	../

CFLAGS		:=	-std=c++11

INCLUDES	:= \
	-I$(BASEDIR)/ \
	-I./ \

LIBS		:= \
	-lpthread \

SUBDIRS		:= \

#
#   Target object
#
TARGET_NAME	:=	common

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:= \
	Utils.cpp \


#
#   Configurations
#
include $(BASEDIR)/Config.mak

