#
#   Defines
#
BASEDIR		:=	../

CFLAGS		:=	-std=c++11

INCLUDES	:= \
	-I$(BASEDIR)/ \
	-I$(BASEDIR)/common \
	-I./ \

LIBS		:= \
	-L$(BASEDIR)/common -lcommon \
	-lpthread \
	-lpcsclite \

SUBDIRS		:= \
	it9175 \
	it9175_test \

#
#   Target object
#
TARGET_NAME	:=

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=

#
#   Compile sources
#
SRCS		:=

SRCS_CPP	:=


#
#   Configurations
#
include $(BASEDIR)/Config.mak

