#
#   Defines
#
BASEDIR		:=	../../../
CFLAGS		:=
INCLUDES	:=
LIBS		:=

#
#   Target object
#
TARGET_NAME	:=	tssplitter_lite

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	STATIC

#
#   Compile sources
#
SRCS		:=	tssplitter_lite.c


#
#   Configurations
#
include $(BASEDIR)/Config.mak

