#
#   Defines
#
BASEDIR		:=	../
CFLAGS		:=
INCLUDES	:=
LIBS		:=

#
#   Target object
#
TARGET_NAME	:=	aribstr

#
#   Target type
#     (EXEC/SHARED/STATIC/OBJECT)
#
TARGET_TYPE	:=	SHARED

#
#   Compile sources
#
SRCS		:=	aribstr.c


#
#   Configurations
#
include $(BASEDIR)/Config.mak

